export default {
  //playerMutations
  OVERWRITE_PLAYER_DATA: "OVERWRITE_PLAYER_DATA",
  INCREASE_PLAYER_STAT: "INCREASE_PLAYER_STAT",
  DECREASE_PLAYER_STAT: "DECREASE_PLAYER_STAT",
  ADD_TO_PLAYER_LOG: "ADD_TO_PLAYER_LOG",
  CLEAR_PLAYER_LOG: "CLEAR_PLAYER_LOG",

  //monster mutations
  OVERWRITE_MONSTER_DATA: "OVERWRITE_MONSTER_DATA",
  INCREASE_MONSTER_STAT: "INCREASE_MONSTER_STAT",
  DECREASE_MONSTER_STAT: "DECREASE_MONSTER_STAT",
  ADD_TO_MONSTER_LOG: "ADD_TO_MONSTER_LOG",
  CLEAR_MONSTER_LOG: "CLEAR_MONSTER_LOG",
};
